name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-react-client:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: install dependencies
        working-directory: ./client
        # there's some kind of broken typescript dependency in the tangle of dependencies
        # by create-react-app, TODO: fix this somehow, for now we'll use --force as
        # a ~~workaround~~ band-aid
        run: npm install --force

        # I guess there's no need to build the react app for tests? yeppers

      - name: test
        working-directory: ./client
        run: npm run test


  test-express-server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/testb?schema=public"    

    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: install dependencies
        working-directory: ./server
        run: npm install

      - name: init prisma
        working-directory: ./server
        run: npx prisma migrate dev --name init
        
      # no need to build for now, we are not ready to release :3
      # - name: build
      #   working-directory: ./server
      #   run: npm run build

      - name: lint
        working-directory: ./server
        run: npm run lint

      - name: test
        working-directory: ./server
        run: npm run test
