name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-react-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: install dependencies
        working-directory: ./client
        run: npm install

      - name: build
        working-directory: ./client
        run: |
          npm run build
          npm run test

  build-express-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: install dependencies
        working-directory: ./client
        run: npm install
        
      - name: build
        working-directory: ./server
        run: |
          npm run build
          npm run test
